resources:
- repo: self
pool:
 vmImage: 'ubuntu-latest'
trigger:
  branches:
    include: [
      "main"
    ]
  paths:
    include: [
      "/"
    ]
steps:
- task: CopyFiles@2
  displayName: "Copy Files"
  inputs:
    Contents: |
      /**
      !**/.git/**
      !*.yml
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: bicep templates"
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: sources
    publishLocation: Container